In [1]:
# Forward Pass with Matrix Multiplication
import numpy as np

def activation(z):
  return 1/(1+np.exp(-z))

def forwardpass(x,weights,bias):
  weighted_sum=np.dot(x,weights)+bias
  print("Weighted Sum :\n",weighted_sum)
  output=activation(weighted_sum)
  return output

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#weights
weights=np.array([[0.8], [0.2]])

#targets
targets=np.array([[1], [0], [1]])

#bias
bias=np.array([0.1])

print("Input Data :\n",x)

output=forwardpass(x,weights,bias)
print("Output :\n",output)


Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Weighted Sum :
 [[0.56]
 [0.4 ]
 [0.92]]
Output :
 [[0.63645254]
 [0.59868766]
 [0.71504211]]


In [2]:
# Forward Pass with Hidden Layer (Matrix Multiplication)


def forwardpass(x,w1,w2,b1,b2):
  #input to hidden layer
  weighted_sum1=np.dot(x,w1)+b1
  print("Weighted Sum from input layer :\n",weighted_sum1)
  h_in=activation(weighted_sum1)
  #hidden to output layer
  weighted_sum2=np.dot(h_in,w2)+b2
  print("Weighted Sum from hidden layer :\n",weighted_sum2)
  h_out=activation(weighted_sum2)
  return h_out

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#targets
targets=np.array([[1], [0], [1]])

# Weights and biases for the input layer to hidden layer
w1= np.array([[0.8, 0.2], [0.4, 0.9]])
b1 = np.array([0.1, 0.5])

# Weights and bias for the hidden layer to output layer
w2 = np.array([[0.3], [0.7]])
b2= np.array([0.2])

final_output=forwardpass(x,w1,w2,b1,b2)

print("Input Data :\n",x)
print("Output :\n",final_output)


Weighted Sum from input layer :
 [[0.62 0.87]
 [0.54 1.17]
 [1.1  1.47]]
Weighted Sum from hidden layer :
 [[0.88838755]
 [0.92374524]
 [0.9942182 ]]
Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Output :
 [[0.70855731]
 [0.71580461]
 [0.72992029]]


In [5]:
# Forward pass without hidden layer (matrix multiplication) with Keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs):
    model = Sequential()
    model.add(Dense(units=1, activation='sigmoid', input_dim=2))  # Input to output
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x, epochs=100)

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


1/1 [==============================] - 0s 67ms/step

Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]

Output Data :
 [[0.56770736]
 [0.4793672 ]
 [0.57377636]]


In [8]:
# Forward pass with hidden layer (matrix multiplication) with Keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs):
    model = Sequential()
    model.add(Dense(units=2, activation='sigmoid', input_dim=2))  # Input to hidden
    model.add(Dense(units=1, activation='sigmoid'))  # Hidden to output
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x, epochs=100)  # Specify the number of epochs

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


1/1 [==============================] - 0s 50ms/step

Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]

Output Data :
 [[0.439917  ]
 [0.43961316]
 [0.4538533 ]]
