In [1]:
import numpy as np

#create a numpy array
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [5]:
#Broadcasting
b=5
result=arr1*b
print(result)

[ 5 10 15 20 25 30 35 40 45]


In [6]:
#indexing
arr2 = np.array([10, 20, 30, 40, 50])

element = arr2[2]  # Accessing the third element
print('element:',element)

subset = arr2[1:4]  # Extracting elements from index 1 to 3
print('subset',subset)

element: 30
subset [20 30 40]


In [7]:
# Slicing example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_slice = matrix[1, :]  # Extracting the second row
print(row_slice)

column_slice = matrix[:, 1]  # Extracting the second column
print(column_slice)

submatrix = matrix[0:2, 1:]  # Extracting a submatrix from rows 1 and 2, and columns 2 and 3
print(submatrix)

[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]


In [16]:
file_path = '/content/exp2dataset.csv'
data = np.genfromtxt(file_path, delimiter=',')

# Display the head of the data
print("Head of the data:")
print(data[1:3])

# Display the tail of the data
print("\nTail of the data:")
print(data[-2:])

# Display the size of the data
print("\nSize of the data:", data.size)

Head of the data:
[[165349.2  136897.8  471784.1  192261.83]
 [162597.7  151377.59 443898.53       nan]]

Tail of the data:
[[  542.05 51743.15     0.   35673.41]
 [    0.        nan 45173.06 14681.4 ]]

Size of the data: 204


In [17]:
# Remove null values
data = np.nan_to_num(data, nan=0)
print("\nData after removing null values:")
print(data)


Data after removing null values:
[[     0.        0.        0.        0.  ]
 [165349.2  136897.8  471784.1  192261.83]
 [162597.7  151377.59 443898.53      0.  ]
 [153441.51 101145.55 407934.54 191050.39]
 [144372.41 118671.85 383199.62 182901.99]
 [142107.34  91391.77 366168.42 166187.94]
 [131876.9   99814.71 362861.36 156991.12]
 [134615.46      0.   127716.82 156122.51]
 [130298.13 145530.06 323876.68 155752.6 ]
 [120542.52 148718.95 311613.29 152211.77]
 [123334.88 108679.17 304981.62 149759.96]
 [101913.08 110594.11 229160.95 146121.95]
 [100671.96  91790.61 249744.55 144259.4 ]
 [ 93863.75 127320.38 249839.44 141585.52]
 [ 91992.39 135495.07 252664.93 134307.35]
 [119943.24 156547.42 256512.92 132602.65]
 [114523.61 122616.84 261776.23 129917.04]
 [ 78013.11 121597.55 264346.06 126992.93]
 [ 94657.16 145077.58 282574.31 125370.37]
 [ 91749.16 114175.79 294919.57 124266.9 ]
 [ 86419.7  153514.11      0.   122776.86]
 [ 76253.86 113867.3  298664.47 118474.03]
 [ 78389.47 153773.4